
services:
  # Core API Service
  core-api:
    build:
      context: ../backend/core-api
      dockerfile: Dockerfile
    container_name: core-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./env/common.local.env
    networks:
      - app-network
    volumes:
      - ../backend/core-api:/app

networks:
  app-network:
    driver: bridge