name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine Environment
      id: determine-env
      run: echo "MY_PROJECT_ENV=prod" >> $GITHUB_ENV

    - name: Authenticate with Google Clouid
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_SA }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: yes-or-next

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE_URI="us-west1-docker.pkg.dev/yes-or-next/yes-or-next/yes-or-next-${{ env.MY_PROJECT_ENV  }}:latest"
        cd backend/core-api && docker build -t "$IMAGE_URI" .
        docker push "$IMAGE_URI"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-service-${{ env.MY_PROJECT_ENV  }}  \
          --image "us-west1-docker.pkg.dev/yes-or-next/yes-or-next/yes-or-next-${{ env.MY_PROJECT_ENV  }}:latest" \
          --platform managed \
          --region us-west1 \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 1 \
          --project yes-or-next \
          --service-account 84243174586-compute@developer.gserviceaccount.com \
          --set-env-vars MY_ENV=${{ env.MY_PROJECT_ENV }} \
